name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # -------------------------------
    # BUILD BACKEND IMAGE
    # -------------------------------
    - name: Build Backend Image
      run: |
       sudo docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/crud-dd-backend:${{ github.sha }} \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/crud-dd-backend:latest \
          ./backend

    # -------------------------------
    # BUILD FRONTEND IMAGE
    # -------------------------------
    - name: Build Frontend Image
      run: |
        sudo docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/crud-dd-frontend:${{ github.sha }} \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/crud-dd-frontend:latest \
          ./frontend

    # -------------------------------
    # PUSH IMAGES
    # -------------------------------
    - name: Push Images
      run: |
        sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/crud-dd-backend:${{ github.sha }}
        sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/crud-dd-backend:latest
        sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/crud-dd-frontend:${{ github.sha }}
        sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/crud-dd-frontend:latest

    # -------------------------------
    # COPY FILES TO VM
    # -------------------------------
    - name: Upload docker-compose + nginx config
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_KEY }}
        source: "docker-compose.yml,nginx/default.conf"
        target: "~/crud-dd-task-mean-app"

    # -------------------------------
    # DEPLOY ON VM
    # -------------------------------
    - name: Deploy on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_KEY }}
        script: |
          cd ~/crud-dd-task-mean-app
          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          sudo docker-compose pull
          sudo docker-compose up -d --force-recreate

