name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # ------------------------------
    # LOGIN TO DOCKER HUB
    # ------------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ------------------------------
    # BUILD FRONTEND IMAGE
    # ------------------------------
    - name: Build Frontend Image
      run: |
        docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/crud-frontend:${{ github.sha }} \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/crud-frontend:latest \
          ./frontend

    # ------------------------------
    # BUILD BACKEND IMAGE
    # ------------------------------
    - name: Build Backend Image
      run: |
        docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/crud-backend:${{ github.sha }} \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/crud-backend:latest \
          ./backend

    # ------------------------------
    # PUSH IMAGES TO DOCKER HUB
    # ------------------------------
    - name: Push Images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/crud-frontend:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/crud-frontend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/crud-backend:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/crud-backend:latest

    # ------------------------------
    # COPY FILES TO SERVER
    # ------------------------------
    - name: Upload docker-compose + Nginx config to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_KEY }}
        source: "docker-compose.yml,nginx/default.conf"
        target: "~/crud-app"

    # ------------------------------
    # DEPLOY TO SERVER
    # ------------------------------
    - name: Deploy on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_KEY }}
        script: |
          cd ~/crud-app
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker-compose pull
          docker-compose up -d --force-recreate

